// Generated by CoffeeScript 1.3.3
var app, assets, express, fs, loadJSDir, loadJSFile, port, stylus;

express = require('express');

stylus = require('stylus');

assets = require('connect-assets');

fs = require("fs");

app = express();

app.use(assets());

console.log("Static Dir: " + process.cwd() + '/public');

app.use(express["static"](process.cwd() + '/public'));

app.set('view engine', 'jade');

loadJSFile = function(file) {
  var assetName, stat;
  stat = fs.statSync(file);
  if (stat != null ? stat.isDirectory() : void 0) {
    return loadJSDir(file);
  } else {
    assetName = (((file.replace("assets/js", "")).replace(".coffee", "")).replace(".js", "")).slice(1);
    console.log("Assetizing " + assetName);
    return js(assetName);
  }
};

loadJSDir = function(dirPath) {
  var file, files, _i, _len;
  files = fs.readdirSync(dirPath);
  for (_i = 0, _len = files.length; _i < _len; _i++) {
    file = files[_i];
    loadJSFile("" + dirPath + "/" + file);
  }
  return true;
};

loadJSFile("assets/js");

app.get('/', function(req, resp) {
  return resp.render('index');
});

port = process.env.PORT || process.env.VMC_APP_PORT || 3000;

app.listen(port, function() {
  return console.log("Listening on " + port + "\nPress CTRL-C to stop server.");
});
