// Generated by CoffeeScript 1.3.3
var BaseControllers, HomeController,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

BaseControllers = require("./_base");

HomeController = (function(_super) {

  __extends(HomeController, _super);

  function HomeController() {
    return HomeController.__super__.constructor.apply(this, arguments);
  }

  HomeController.prototype.get = {
    "/": "default",
    "/about": "about"
  };

  HomeController.prototype["default"] = function(req, resp) {
    return resp.render("index");
  };

  HomeController.prototype.about = function(req, resp) {
    return resp.render("about");
  };

  return HomeController;

})(BaseControllers.BaseRouteController);

module.exports = new HomeController;
